// components/QuizView.jsx — quiz UI: generate, answer, and review results
import { useQuiz } from '../hooks/useQuiz'
import useLearnStore from '../store/useLearnStore'

export default function QuizView() {
  const { subject } = useLearnStore()
  const { questions, answers, result, loading, error, generate, choose, submit, allAnswered } = useQuiz()

  // Results screen
  if (result) {
    return (
      <div style={styles.wrap}>
        <div style={styles.scoreCard}>
          <div style={styles.scoreIcon}>{result.score >= result.total / 2 ? '🎉' : '📚'}</div>
          <div style={styles.scoreText}>{result.score} / {result.total}</div>
          <div style={styles.scoreLabel}>{result.score === result.total ? 'Perfect score!' : result.score >= result.total / 2 ? 'Good job!' : 'Keep practicing!'}</div>
        </div>

        <div style={styles.reviewList}>
          {result.results.map((r, i) => (
            <div key={r.id} style={{ ...styles.reviewItem, borderLeft: `4px solid ${r.correct ? '#22c55e' : '#ef4444'}` }}>
              <div style={styles.reviewQ}>{questions[i].question}</div>
              <div style={{ color: r.correct ? '#16a34a' : '#dc2626', fontSize: 13, marginBottom: 4 }}>
                {r.correct ? '✓ Correct' : `✗ You chose ${r.chosen} · Correct: ${r.answer}`}
              </div>
              <div style={styles.reviewExp}>{questions[i].explanation}</div>
            </div>
          ))}
        </div>

        <button style={styles.btnPrimary} onClick={generate}>Try Another Quiz</button>
      </div>
    )
  }

  // Empty state
  if (questions.length === 0) {
    return (
      <div style={styles.empty}>
        <div style={styles.emptyIcon}>🧠</div>
        <p style={styles.emptyText}>Test your knowledge of <strong>{subject}</strong></p>
        <p style={styles.emptySubtext}>5 multiple choice questions generated by AI based on your level</p>
        <button style={styles.btnPrimary} onClick={generate} disabled={loading}>
          {loading ? 'Generating...' : 'Generate Quiz'}
        </button>
        {error && <div style={styles.error}>{error}</div>}
      </div>
    )
  }

  // Quiz screen
  return (
    <div style={styles.wrap}>
      <div style={styles.quizHeader}>
        <span style={styles.quizTitle}>{subject} Quiz</span>
        <span style={styles.quizProgress}>{Object.keys(answers).length} / {questions.length} answered</span>
      </div>

      <div style={styles.questionList}>
        {questions.map((q, i) => (
          <div key={q.id} style={styles.questionCard}>
            <div style={styles.questionText}><span style={styles.qNum}>Q{i + 1}.</span> {q.question}</div>
            <div style={styles.options}>
              {q.options.map((opt) => {
                const letter = opt.charAt(0)
                const chosen = answers[q.id] === letter
                return (
                  <button
                    key={opt}
                    style={{ ...styles.option, ...(chosen ? styles.optionChosen : {}) }}
                    onClick={() => choose(q.id, opt)}
                  >
                    {opt}
                  </button>
                )
              })}
            </div>
          </div>
        ))}
      </div>

      {error && <div style={styles.error}>{error}</div>}

      <div style={styles.actions}>
        <button style={{ ...styles.btnSecondary }} onClick={generate} disabled={loading}>Regenerate</button>
        <button
          style={{ ...styles.btnPrimary, opacity: allAnswered ? 1 : 0.4 }}
          disabled={!allAnswered || loading}
          onClick={submit}
        >
          {loading ? 'Submitting...' : 'Submit Quiz'}
        </button>
      </div>
    </div>
  )
}

const styles = {
  wrap: { padding: '28px 32px', overflowY: 'auto', height: '100%', display: 'flex', flexDirection: 'column', gap: 20 },
  empty: { flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 12, textAlign: 'center', padding: 40 },
  emptyIcon: { fontSize: 52 },
  emptyText: { fontSize: 16, color: '#1e293b' },
  emptySubtext: { fontSize: 13, color: '#64748b', marginBottom: 8 },

  quizHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  quizTitle: { fontWeight: 700, fontSize: 18, color: '#1e293b' },
  quizProgress: { fontSize: 13, color: '#6366f1', fontWeight: 600 },

  questionList: { display: 'flex', flexDirection: 'column', gap: 16 },
  questionCard: { background: '#fff', borderRadius: 12, padding: '18px 20px', border: '1px solid #e2e8f0' },
  questionText: { fontSize: 15, fontWeight: 500, color: '#1e293b', marginBottom: 14, lineHeight: 1.5 },
  qNum: { color: '#6366f1', fontWeight: 700, marginRight: 6 },
  options: { display: 'flex', flexDirection: 'column', gap: 8 },
  option: { padding: '10px 14px', borderRadius: 8, border: '2px solid #e2e8f0', background: '#f8fafc', fontSize: 14, color: '#334155', cursor: 'pointer', textAlign: 'left', fontWeight: 500 },
  optionChosen: { borderColor: '#6366f1', background: '#eef2ff', color: '#6366f1' },

  actions: { display: 'flex', justifyContent: 'flex-end', gap: 10, paddingTop: 4 },
  btnPrimary: { padding: '11px 28px', borderRadius: 10, border: 'none', background: '#6366f1', color: '#fff', fontWeight: 600, fontSize: 14, cursor: 'pointer' },
  btnSecondary: { padding: '11px 28px', borderRadius: 10, border: '2px solid #e2e8f0', background: '#fff', color: '#64748b', fontWeight: 600, fontSize: 14, cursor: 'pointer' },

  scoreCard: { display: 'flex', flexDirection: 'column', alignItems: 'center', background: '#fff', borderRadius: 16, padding: '32px 24px', border: '1px solid #e2e8f0', gap: 8 },
  scoreIcon: { fontSize: 48 },
  scoreText: { fontSize: 40, fontWeight: 800, color: '#6366f1' },
  scoreLabel: { fontSize: 16, color: '#64748b', fontWeight: 500 },

  reviewList: { display: 'flex', flexDirection: 'column', gap: 12 },
  reviewItem: { background: '#fff', borderRadius: 10, padding: '14px 16px', border: '1px solid #e2e8f0' },
  reviewQ: { fontSize: 14, fontWeight: 600, color: '#1e293b', marginBottom: 6 },
  reviewExp: { fontSize: 13, color: '#64748b', lineHeight: 1.5 },

  error: { color: '#ef4444', fontSize: 13, background: '#fef2f2', padding: '10px 14px', borderRadius: 8 },
}
